import CoreGraphics
import ImageIO
import LatticeCore
import SwiftUI
import UniformTypeIdentifiers

/// The app icon, generated by the game's own vocabulary: a dense field of
/// dots and drawn lines with a "5" ERASED out of it — the glyph is negative
/// space, blank paper carved from the drawing. The field is a seeded greedy
/// packing that honours the segment-reuse rule, so what remains reads as a
/// legal position. Deterministic forever for a given seed.
public enum IconArt {
    public enum Appearance: String, CaseIterable {
        case light
        case dark
        /// iOS tinted icons: white art on transparent; the system tints it.
        case tinted
    }

    static let gridMax = 14

    /// The drawn-line field: seeded shuffle-greedy over all candidate lines,
    /// keeping any whose unit segments are all fresh (5T bookkeeping).
    static func fieldLines(seed: UInt64 = 5) -> [Line] {
        let gridRange = 0...gridMax
        var candidates: [Line] = []
        for x in gridRange {
            for y in gridRange {
                for axis in LatticeCore.Axis.allCases {
                    for length in [3, 4, 5] {
                        let line = Line(origin: Point(x, y), axis: axis, length: length)
                        guard
                            line.points.allSatisfy({
                                gridRange.contains($0.x) && gridRange.contains($0.y)
                            })
                        else { continue }
                        candidates.append(line)
                    }
                }
            }
        }
        candidates.sort {
            ($0.origin.x, $0.origin.y, $0.axis.rawValue, $0.length)
                < ($1.origin.x, $1.origin.y, $1.axis.rawValue, $1.length)
        }
        var rng = SplitMix64(seed: seed)
        var order = Array(candidates.indices)
        for index in order.indices.reversed() where index > 0 {
            order.swapAt(index, Int(rng.next() % UInt64(index + 1)))
        }
        var used = Set<Segment>()
        var picked: [Line] = []
        for candidateIndex in order {
            let line = candidates[candidateIndex]
            let segments = line.segments
            guard segments.allSatisfy({ !used.contains($0) }) else { continue }
            used.formUnion(segments)
            picked.append(line)
        }
        return picked
    }

    /// The "5", as a single open stroke in unit space — erased fat from the
    /// field, so the digit is what the drawing leaves blank.
    static func glyphPath(in size: CGFloat) -> Path {
        var path = Path()
        func pt(_ x: CGFloat, _ y: CGFloat) -> CGPoint {
            CGPoint(x: x * size, y: y * size)
        }
        path.move(to: pt(0.68, 0.20))
        path.addLine(to: pt(0.36, 0.20))
        path.addLine(to: pt(0.33, 0.47))
        path.addCurve(to: pt(0.52, 0.42), control1: pt(0.38, 0.43), control2: pt(0.45, 0.41))
        path.addCurve(to: pt(0.70, 0.62), control1: pt(0.63, 0.44), control2: pt(0.70, 0.51))
        path.addCurve(to: pt(0.50, 0.80), control1: pt(0.70, 0.73), control2: pt(0.62, 0.80))
        path.addCurve(to: pt(0.32, 0.72), control1: pt(0.41, 0.80), control2: pt(0.34, 0.76))
        return path
    }

    @MainActor
    public static func render(pixels: Int, appearance: Appearance) -> CGImage? {
        let renderer = ImageRenderer(
            content: IconView(appearance: appearance).frame(
                width: CGFloat(pixels), height: CGFloat(pixels)))
        renderer.scale = 1
        return renderer.cgImage
    }

    @MainActor
    public static func pngData(pixels: Int, appearance: Appearance) -> Data? {
        guard let image = render(pixels: pixels, appearance: appearance) else { return nil }
        let data = NSMutableData()
        guard
            let destination = CGImageDestinationCreateWithData(
                data, UTType.png.identifier as CFString, 1, nil)
        else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return data as Data
    }
}

struct IconView: View {
    let appearance: IconArt.Appearance

    private var paper: Color {
        switch appearance {
        case .light: return paletteRGB(0xFA_F8F4)
        case .dark: return paletteRGB(0x23_242A)
        case .tinted: return .clear
        }
    }

    private var ink: Color {
        switch appearance {
        case .light: return paletteRGB(0x1C_1B19)
        case .dark: return paletteRGB(0xEC_EBE6)
        case .tinted: return .white
        }
    }

    var body: some View {
        Canvas { context, size in
            if appearance != .tinted {
                context.fill(Path(CGRect(origin: .zero, size: size)), with: .color(paper))
            }
            // 15×15 lattice with a half-cell outer margin → 16 cells across.
            let cell = size.width / CGFloat(IconArt.gridMax + 2)
            func position(_ p: Point) -> CGPoint {
                CGPoint(x: cell * (CGFloat(p.x) + 1), y: cell * (CGFloat(p.y) + 1))
            }
            for line in IconArt.fieldLines() {
                guard let first = line.points.first, let last = line.points.last else {
                    continue
                }
                var path = Path()
                path.move(to: position(first))
                path.addLine(to: position(last))
                context.stroke(
                    path, with: .color(ink.opacity(0.55)),
                    style: StrokeStyle(lineWidth: cell * 0.10, lineCap: .round))
            }
            for x in 0...IconArt.gridMax {
                for y in 0...IconArt.gridMax {
                    let center = position(Point(x, y))
                    let radius = cell * 0.20
                    context.fill(
                        Path(
                            ellipseIn: CGRect(
                                x: center.x - radius, y: center.y - radius,
                                width: radius * 2, height: radius * 2)),
                        with: .color(ink))
                }
            }
            // Erase the "5": paper over ink — or a true punch-out for the
            // tinted (transparent) variant.
            let glyphStyle = StrokeStyle(
                lineWidth: size.width * 0.13, lineCap: .round, lineJoin: .round)
            if appearance == .tinted {
                context.blendMode = .destinationOut
                context.stroke(
                    IconArt.glyphPath(in: size.width), with: .color(.black),
                    style: glyphStyle)
            } else {
                context.stroke(
                    IconArt.glyphPath(in: size.width), with: .color(paper),
                    style: glyphStyle)
            }
        }
    }
}
