import CoreGraphics
import ImageIO
import LatticeCore
import SwiftUI
import UniformTypeIdentifiers

/// The app icon, generated by the game's own vocabulary: a dense field of
/// dots and drawn lines whose NEGATIVE SPACE forms a "5" — the glyph is
/// lattice-aligned blank paper, and every edge of it is exactly where lines
/// end, dot to dot. The field is a seeded greedy packing honouring the
/// segment-reuse rule, plus a boundary pass that traces the glyph tightly.
/// Deterministic forever for a given seed.
public enum IconArt {
    public enum Appearance: String, CaseIterable {
        case light
        case dark
        /// iOS tinted icons: white art on transparent; the system tints it.
        case tinted
    }

    static let gridMax = 14

    /// The "5" as a chunky pixel glyph (2-cell strokes, 7×11, centred —
    /// margins 4/4 on the 15-point grid) — these lattice points stay empty;
    /// nothing is ever drawn on or through them.
    private static let glyphRows = [
        "#######",
        "#######",
        "##.....",
        "##.....",
        "######.",
        "#######",
        ".....##",
        ".....##",
        "##...##",
        "#######",
        ".#####.",
    ]

    static var glyphPoints: Set<Point> {
        var points = Set<Point>()
        for (rowIndex, row) in glyphRows.enumerated() {
            for (columnIndex, char) in row.enumerated() where char == "#" {
                points.insert(Point(columnIndex + 4, rowIndex + 2))
            }
        }
        return points
    }

    private static func neighboursGlyph(_ p: Point, _ glyph: Set<Point>) -> Bool {
        for dx in -1...1 {
            for dy in -1...1 where dx != 0 || dy != 0 {
                if glyph.contains(Point(p.x + dx, p.y + dy)) { return true }
            }
        }
        return false
    }

    /// The drawn-line field: seeded shuffle-greedy over candidate lines
    /// avoiding the glyph (5T segment bookkeeping), then a boundary pass —
    /// every still-free segment touching the glyph's neighbourhood is drawn,
    /// so the blank digit's edge is exactly where lines end.
    static func fieldLines(seed: UInt64 = 5) -> [Line] {
        let glyph = glyphPoints
        let gridRange = 0...gridMax
        func inField(_ p: Point) -> Bool {
            gridRange.contains(p.x) && gridRange.contains(p.y) && !glyph.contains(p)
        }
        var candidates: [Line] = []
        for x in gridRange {
            for y in gridRange {
                for axis in LatticeCore.Axis.allCases {
                    for length in [3, 4, 5] {
                        let line = Line(origin: Point(x, y), axis: axis, length: length)
                        guard line.points.allSatisfy(inField) else { continue }
                        candidates.append(line)
                    }
                }
            }
        }
        candidates.sort {
            ($0.origin.x, $0.origin.y, $0.axis.rawValue, $0.length)
                < ($1.origin.x, $1.origin.y, $1.axis.rawValue, $1.length)
        }
        var rng = SplitMix64(seed: seed)
        var order = Array(candidates.indices)
        for index in order.indices.reversed() where index > 0 {
            order.swapAt(index, Int(rng.next() % UInt64(index + 1)))
        }
        var used = Set<Segment>()
        var picked: [Line] = []
        for candidateIndex in order {
            let line = candidates[candidateIndex]
            let segments = line.segments
            guard segments.allSatisfy({ !used.contains($0) }) else { continue }
            used.formUnion(segments)
            picked.append(line)
        }
        picked += boundaryTrace(inField: inField, glyph: glyph, used: &used)
        // Organic edges: thin the outermost ring — a seeded share of lines
        // touching it is dropped, leaving frontier gaps and a few
        // unconnected dots, like a live game's edge.
        var edgeRng = SplitMix64(seed: seed ^ 0xED6E)
        picked = picked.filter { line in
            let touchesEdge = line.points.contains {
                $0.x == 0 || $0.y == 0 || $0.x == gridMax || $0.y == gridMax
            }
            guard touchesEdge else { return true }
            return edgeRng.next() % 100 < 55
        }
        return picked
    }

    // Trace the glyph edge with the remaining free segments, so the digit
    // is cut by line-ends, not by absence alone.
    private static func boundaryTrace(
        inField: (Point) -> Bool, glyph: Set<Point>, used: inout Set<Segment>
    ) -> [Line] {
        var picked: [Line] = []
        for x in 0...gridMax {
            for y in 0...gridMax {
                for axis in LatticeCore.Axis.allCases {
                    let line = Line(origin: Point(x, y), axis: axis, length: 2)
                    let points = line.points
                    guard points.allSatisfy(inField),
                        points.contains(where: { neighboursGlyph($0, glyph) }),
                        line.segments.allSatisfy({ !used.contains($0) })
                    else { continue }
                    used.formUnion(line.segments)
                    picked.append(line)
                }
            }
        }
        return picked
    }

    @MainActor
    public static func render(pixels: Int, appearance: Appearance) -> CGImage? {
        let renderer = ImageRenderer(
            content: IconView(appearance: appearance, pixels: pixels).frame(
                width: CGFloat(pixels), height: CGFloat(pixels)))
        renderer.scale = 1
        return renderer.cgImage
    }

    @MainActor
    public static func pngData(pixels: Int, appearance: Appearance) -> Data? {
        guard let image = render(pixels: pixels, appearance: appearance) else { return nil }
        let data = NSMutableData()
        guard
            let destination = CGImageDestinationCreateWithData(
                data, UTType.png.identifier as CFString, 1, nil)
        else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return data as Data
    }
}

struct IconView: View {
    let appearance: IconArt.Appearance
    var pixels: Int = 1024

    /// Tiny raster sizes (16/32 pt Mac slots) lose the thin strokes — the
    /// same art renders bolder there.
    private var isTiny: Bool { pixels <= 32 }

    private var paper: Color {
        switch appearance {
        case .light: return paletteRGB(0xFA_F8F4)
        case .dark: return paletteRGB(0x23_242A)
        case .tinted: return .clear
        }
    }

    private var ink: Color {
        switch appearance {
        case .light: return paletteRGB(0x1C_1B19)
        case .dark: return paletteRGB(0xEC_EBE6)
        case .tinted: return .white
        }
    }

    var body: some View {
        Canvas { context, size in
            if appearance != .tinted {
                context.fill(Path(CGRect(origin: .zero, size: size)), with: .color(paper))
            }
            // 15×15 lattice with a half-cell outer margin → 16 cells across.
            let cell = size.width / CGFloat(IconArt.gridMax + 2)
            func position(_ p: Point) -> CGPoint {
                CGPoint(x: cell * (CGFloat(p.x) + 1), y: cell * (CGFloat(p.y) + 1))
            }
            let glyph = IconArt.glyphPoints
            for line in IconArt.fieldLines() {
                guard let first = line.points.first, let last = line.points.last else {
                    continue
                }
                var path = Path()
                path.move(to: position(first))
                path.addLine(to: position(last))
                context.stroke(
                    path, with: .color(ink.opacity(isTiny ? 0.85 : 0.55)),
                    style: StrokeStyle(
                        lineWidth: cell * (isTiny ? 0.18 : 0.10), lineCap: .round))
            }
            for x in 0...IconArt.gridMax {
                for y in 0...IconArt.gridMax {
                    let p = Point(x, y)
                    guard !glyph.contains(p) else { continue }
                    let center = position(p)
                    let radius = cell * (isTiny ? 0.28 : 0.20)
                    context.fill(
                        Path(
                            ellipseIn: CGRect(
                                x: center.x - radius, y: center.y - radius,
                                width: radius * 2, height: radius * 2)),
                        with: .color(ink))
                }
            }
        }
    }
}
